### ISSUE TITLE
oxd path lookup failed

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#24]
Testing environment: Ubuntu 14

Getting this error:
```
01:23:10 05/03/18 Failed to find oxd package in folder /opt/dist/oxd !
01:23:10 05/03/18 ***** Error caught in main loop *****
01:23:10 05/03/18 Traceback (most recent call last):
  File "./setup_cred_mgr.py", line 592, in <module>
    installObject.install_gluu_components()
  File "./setup_cred_mgr.py", line 154, in install_gluu_components
    self.install_oxd_server()
  File "./setup_cred_mgr.py", line 215, in install_oxd_server
    sys.exit(0)
SystemExit: 0
```

Looks like a side effect of `detect_os_type` in `setup.py` as in #22

**Comment by yurem** [comment]
It works well in latest script
