### ISSUE TITLE
subservices cannot start

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/post-installation-setup#25]
Testing environment: ubuntu14

oxd/oxauth/cred-manager services not starting

```
01:37:03 05/03/18 Running: chmod +x /opt/oxd-server/bin/oxd-start.sh
01:37:03 05/03/18 Running: /sbin/service oxd-server start
01:37:03 05/03/18 Error running command : /sbin/service oxd-server start
01:37:03 05/03/18 Traceback (most recent call last):
  File "/install/community-edition-setup/setup.py", line 2549, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

```
01:37:06 05/03/18 Running: /sbin/service oxauth restart
01:37:06 05/03/18 Error running command : /sbin/service oxauth restart
01:37:06 05/03/18 Traceback (most recent call last):
  File "/install/community-edition-setup/setup.py", line 2549, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

```
01:37:06 05/03/18 Running: /sbin/service cred-manager start
01:37:06 05/03/18 Error running command : /sbin/service cred-manager start
01:37:06 05/03/18 Traceback (most recent call last):
  File "/install/community-edition-setup/setup.py", line 2549, in run
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by yurem** [comment]
Fixed
